# component/config.py

FPS = 60

# 셰이커 관련
SHAKE_THRESHOLD = 1.0
POUR_START_ANGLE = -30.0
POUR_MAX_ANGLE = -110.0

MAX_SHAKER_VOLUME = 4.0
POUR_RATE = 1.2

# 잔 관련
GLASS_CAPACITY = MAX_SHAKER_VOLUME

# 물줄기 관련
STREAM_BASE_WIDTH = 4
STREAM_EXTRA_WIDTH = 6

STREAM_WIGGLE_AMP = 1.2
STREAM_WIGGLE_AMP_EXTRA = 1.0
STREAM_WIGGLE_FREQ = 14.0
