# config.py
FPS = 60

# 셰이커
SHAKE_THRESHOLD = 2.0
POUR_START_ANGLE = -30
POUR_MAX_ANGLE = -100
MAX_SHAKER_VOLUME = 4.0
VOLUME_PER_PARTICLE = 0.003

# 잔
GLASS_FILL_PER_PARTICLE = 0.005
SURFACE_DROPLET_LIFE = (0.3, 0.8)
SURFACE_DROPLET_RADIUS = 3